# Configuration for Simultaneous Multi-Algorithm Runs
# Reduced resource usage per experiment

# Hardware Configuration - Reduced for parallel experiments
hardware:
  device: mps  # GPU acceleration enabled
  num_workers: 2  # Reduced from 4 to 2 for parallel runs
  max_parallel_processes: 1  # Single threaded per experiment
  use_multiprocessing: false  # Keep disabled
  memory_limit_gb: 12  # Reduced from 24 to 12 per experiment

# Datasets (same as main config)
datasets:
  mnist:
    name: "MNIST"
    input_size: 784
    num_classes: 10
    batch_sizes: [64, 128, 256, 512]  # Larger batches for better GPU utilization
  cifar10:
    name: "CIFAR-10"
    input_size: [3, 32, 32]
    num_classes: 10
    batch_sizes: [64, 128, 256, 512]  # Larger batches for better GPU utilization

# Neural Network Architecture Search Space
hyperparameters:
  learning_rate:
    min: 0.0001
    max: 0.1
    log_scale: true
  batch_size: [128, 256, 512, 1024]  # Larger batches for dedicated GPU memory
  dropout_rate:
    min: 0.0
    max: 0.5
  hidden_units: [64, 128, 256, 512]
  optimizer: ["adam", "sgd", "rmsprop"]
  weight_decay:
    min: 0.0
    max: 0.01

# Evolutionary Algorithm Parameters (same as main config)
algorithms:
  genetic_algorithm:
    population_size: 12
    generations: 20
    mutation_rate: 0.1
    crossover_rate: 0.8
    tournament_size: 3
  
  differential_evolution:
    population_size: 12
    generations: 20
    mutation_factor: 0.8
    crossover_rate: 0.7
  
  particle_swarm:
    population_size: 12
    generations: 20
    inertia_weight: 0.7
    cognitive_factor: 1.5
    social_factor: 1.5
  
  grid_search:
    max_evaluations: 60
  
  random_search:
    max_evaluations: 60

# Training Configuration
training:
  max_epochs: 50
  early_stopping_patience: 10
  validation_split: 0.2
  test_split: 0.1

# Execution Modes
execution_modes:
  full_run:
    algorithms: ["grid", "random", "ga", "de", "pso"]
    datasets: ["mnist", "cifar10"]
    runs_per_algorithm: 3
  
  light_run:
    algorithms: ['grid', 'random', 'ga', 'de', 'pso']
    datasets: ['mnist']
    runs_per_algorithm: 1
    max_generations: 5
    population_size: 6  
    max_epochs: 3
    max_evaluations: 30

# Output Configuration
output:
  save_checkpoints: true
  checkpoint_frequency: 5
  save_convergence_plots: true
  save_best_models: true
  export_results_csv: true
  export_results_json: true

# Random Seed for Reproducibility
random_seed: 42

# Logging
logging:
  level: "INFO"
  save_logs: true
  log_file: "experiment.log"